<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <AssemblyName>NanoPic.App.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../TestCompatibility.cs" Link="TestCompatibility.cs" />
    <ProjectReference Include="../../src/NanoPic.App/NanoPic.App.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
