<Project>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <Version>3.2.1</Version>
    <AssemblyVersion>3.2.1.0</AssemblyVersion>
    <FileVersion>3.2.1.0</FileVersion>
    <Authors>Roz</Authors>
    <Company>NanoPic</Company>
    <Product>NanoPic</Product>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <Compile Include="$(MSBuildThisFileDirectory)build\NetFrameworkCompatibility.cs"
             Link="Properties\NetFrameworkCompatibility.cs" />
  </ItemGroup>
</Project>
