<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>NanoPic</AssemblyName>
    <RootNamespace>NanoPic.App</RootNamespace>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>NanoPic.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NanoPic.Core/NanoPic.Core.csproj" />
    <ProjectReference Include="../NanoPic.Codecs/NanoPic.Codecs.csproj" />
    <ProjectReference Include="../NanoPic.Infrastructure/NanoPic.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fody" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="THIRD-PARTY-NOTICES.txt" />
    <None Include="FodyWeavers.xml" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="NanoPic.ico" />
  </ItemGroup>
</Project>
