<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AssemblyName>NanoPic.Codecs.Tests</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../assets/legacy-inputs/*" Link="assets/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../TestCompatibility.cs" Link="TestCompatibility.cs" />
    <Compile Include="../../src/NanoPic.Codecs/MagickNetCodecEngine.cs" Link="Baseline/MagickNetCodecEngine.cs" />
    <Compile Include="../../src/NanoPic.Codecs/MagickNetImageCodec.cs" Link="Baseline/MagickNetImageCodec.cs" />
    <ProjectReference Include="../../src/NanoPic.Codecs/NanoPic.Codecs.csproj" />
    <ProjectReference Include="../../src/NanoPic.Core/NanoPic.Core.csproj" />
    <PackageReference Include="Magick.NET-Q8-x64" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
